{% set name = "amazon-braket-sdk" %}
{% set version = "1.68.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-sdk-{{ version }}.tar.gz
  sha256: 4ba123b41ec94d71460facb7f6bbbb3fe4df40d9caf161a56f47c3a55437917a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cloudpickle ==2.2.1
    - setuptools
    - openpulse
    - openqasm3
    - oqpy >=0.2.1,<0.3.dev0
    - amazon-braket-schemas >=1.19.1
    - amazon-braket-default-simulator >=1.19.1
    - backoff
    - boltons
    - boto3 >=1.28.53
    - nest-asyncio
    - networkx
    - numpy
    - python >=3.9
    - sympy

test:
  imports:
    - braket
    - braket._sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-sdk-python
  summary: An open source library for interacting with quantum computing devices on Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://amazon-braket-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
