{% set name = "amazon-braket-sdk" %}
{% set version = "1.48.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-sdk-{{ version }}.tar.gz
  sha256: 766192eb1f50e4ae9b684599878c26f848c5f49faa8d1513e03bc179b878e3c4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.2
  run:
    - botocore <1.29.160
    - setuptools
    - openpulse
    - openqasm3
    - oqpy >=0.1.1,<0.2.dev0
    - amazon-braket-schemas >=1.17.0
    - amazon-braket-default-simulator >=1.15.0
    - backoff
    - boltons
    - boto3 >=1.22.3,<1.26.160
    - nest-asyncio
    - networkx
    - numpy
    - python >=3.8.2
    - sympy

test:
  imports:
    - braket
    - braket._sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-sdk-python
  summary: An open source library for interacting with quantum computing devices on Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://amazon-braket-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
