{% set name = "amazon-braket-sdk" %}
{% set version = "1.36.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-sdk-{{ version }}.tar.gz
  sha256: 32f77a0735a40611a67888294b6c95b478ad2a07723029c94708fbb0d01a7412

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.2
  run:
    - setuptools
    - openpulse
    - openqasm3
    - oqpy >=0.1.1,<0.2.dev0
    - amazon-braket-schemas >=1.14.0
    - amazon-braket-default-simulator >=1.11.0
    - backoff
    - boltons
    - boto3 >=1.22.3
    - nest-asyncio
    - networkx
    - numpy
    - python >=3.8.2
    - sympy

test:
  imports:
    - braket
    - braket._sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-sdk-python
  summary: An open source library for interacting with quantum computing devices on Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://amazon-braket-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
