{% set name = "amazon-braket-sdk" %}
{% set version = "1.50.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-sdk-{{ version }}.tar.gz
  sha256: 5e42a0de120e585ca360e7f9f04850647d551c78984849ab594e0e3e44beb1be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.2
  run:
    - botocore <1.29.160
    - setuptools
    - openpulse
    - openqasm3
    - oqpy >=0.1.1,<0.2.dev0
    - amazon-braket-schemas >=1.18.0
    - amazon-braket-default-simulator >=1.18.1
    - backoff
    - boltons
    - boto3 >=1.22.3
    - nest-asyncio
    - networkx
    - numpy
    - python >=3.8.2
    - sympy

test:
  imports:
    - braket
    - braket._sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-sdk-python
  summary: An open source library for interacting with quantum computing devices on Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://amazon-braket-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
