{% set name = "amazon-braket-sdk" %}
{% set version = "1.91.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 197738a1b2c9bdf8a079292fcca5f092ed12644dcdf40feaba4e5308e48853d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - backports.entry-points-selectable
    - cloudpickle ==2.2.1
    - openpulse
    - openqasm3
    - oqpy >=0.3.5,<0.4.dev0
    - amazon-braket-schemas >=1.23.0
    - amazon-braket-default-simulator >=1.26.0
    - backoff
    - boltons
    - boto3 >=1.28.53
    - nest-asyncio
    - networkx
    - numpy
    - python >={{ python_min }}
    - sympy

test:
  imports:
    - braket
    - braket._sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/amazon-braket-sdk-python
  summary: An open source library for interacting with quantum computing devices on Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://amazon-braket-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
